AWSTemplateFormatVersion: 2010-09-09
Description: Create an SNS Topic to publish results for AWS Config Rule Access-Key-Rotation
Parameters:
  TargetAccounts:
    Type: String
    Description: The list of target AWS Account Ids, comma-separated
Resources:
  SNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: >-
        SNS topic to distribute information regarding access key rotation rule
        non-compliance
      TopicName: AccessKeyRotationTopic
      KmsMasterKeyId: alias/aws/sns
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: SnsTopicPublishPolicy
          Action: sns:Publish
          Effect: Allow
          Resource: 
          - !Join
            - ''
            - - 'arn:aws:sns:'
              - !Ref 'AWS::Region'
              - ":"
              - !Ref 'AWS::AccountId'
              - ':AccessKeyRotationTopic'          
          Principal:
            AWS: 
              !Split 
                - ","
                - !Ref TargetAccounts
      Topics:
      - !Ref SNSTopic
Outputs:
  SNSTopicOutput:
    Description: The SNS Topic that was created
    Value: !Ref SNSTopic
